import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsIn,
  IsNotEmpty,
  IsNumber,
  IsObject,
  IsOptional,
  IsString,
  Matches,
  Max,
  Min,
} from 'class-validator';

export class VerifyPaymentDto {
  @ApiProperty({
    example: 'order_QHI2xgVvRyJmQb',
    description: 'Order id returned by POST /api/v1/orders.',
  })
  @IsString()
  @IsNotEmpty()
  razorpay_order_id: string;

  @ApiProperty({
    example: 'pay_QHI3aBcDeFgHiJ',
    description: 'Payment id returned by Razorpay Checkout.',
  })
  @IsString()
  @IsNotEmpty()
  razorpay_payment_id: string;

  @ApiProperty({
    example: '9ef4dffbfd84f1318f6739a3ce19f9d8b4111b1e7e66aebbc6a022f0f6c0e7a1',
    description: 'Signature generated by Razorpay Checkout.',
  })
  @IsString()
  @IsNotEmpty()
  razorpay_signature: string;
}

export class CapturePaymentDto {
  @ApiPropertyOptional({
    example: 499,
    description:
      'Amount in major currency units to capture. Must equal the authorized amount. Omit to capture the full authorized amount fetched from Razorpay.',
  })
  @IsOptional()
  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 3 })
  @Min(1)
  amount?: number;

  @ApiPropertyOptional({ example: 'INR', default: 'INR' })
  @IsOptional()
  @Matches(/^[A-Z]{3}$/, { message: 'currency must be a 3-letter ISO code' })
  currency?: string = 'INR';
}

export class CreateRefundDto {
  @ApiPropertyOptional({
    example: 100,
    description:
      'Refund amount in major currency units. Omit for a full refund of the remaining balance.',
  })
  @IsOptional()
  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 3 })
  @Min(0.01)
  amount?: number;

  @ApiPropertyOptional({
    example: 'optimum',
    enum: ['optimum', 'instant'],
    default: 'optimum',
    description: 'Refund speed. Instant refunds settle to the customer immediately (eligible banks only).',
  })
  @IsOptional()
  @IsIn(['optimum', 'instant'])
  speed?: 'optimum' | 'instant' = 'optimum';

  @ApiPropertyOptional({ example: { reason: 'customer_request' } })
  @IsOptional()
  @IsObject()
  notes?: Record<string, string>;
}
